const homeParams = new URLSearchParams(window.location.search);
const ageHomeParams = homeParams.get('kids') ;
const localeHomeParams = homeParams.get('locale') ;
const settingsAgePathName = new URL(location.href).pathname.split('/')[2];
const settingsLocalePathName = new URL(location.href).pathname.split('/')[1];
const settingsLocale = homeParams.has('locale') ? localeHomeParams : settingsLocalePathName;
const settingsAge = homeParams.has('kids') ? ageHomeParams : settingsAgePathName;
const setAge = settingsAge === 'kids' || ageHomeParams === 'on' ? `&kids=on` : ''; 
const settingsPath = `/?locale=${settingsLocale}${setAge}`;
const homeButton = document.getElementById('homeButton');
homeButton?.setAttribute('href', settingsPath);